
main:
  push:
    - docker:
        image: python:3.13
      stages:
        - name: Build & Push
          script:
            - pip install build twine
            - export TWINE_USERNAME="cnb"
            - export TWINE_PASSWORD=$CNB_TOKEN
            - export TWINE_REPOSITORY_URL="https://pypi.cnb.cool/leecq/pytools/-/packages/simple"
            - python -m build
            - twine upload dist/*