$:
  vscode:
    - runner:
        cpus: 2
      docker:
        # build: images/Dev.Dockerfile
        # 可选择是否同时定义 build 和 image
        # 此时会优先使用 .ide/Dockerfile 构建镜像
        # 如果 .ide/Dockerfile 构建失败，则使用 image 指定的镜像保证环境能启动成功
        # image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker

main:
  push:
    - docker:
        image: python:3.13
      stages:
        - name: Build & Push
          script:
            - pip install build twine
            - export TWINE_USERNAME="cnb"
            - export TWINE_PASSWORD=$CNB_TOKEN
            - export TWINE_REPOSITORY_URL="https://pypi.cnb.cool/leecq/pytools/-/packages/simple"
            - python -m build
            - twine upload dist/*