[project]
name = "translate"
version = "0.1.4"
description = "翻译工具包"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "nltk>=3.9.1",
    "pillow>=11.3.0",
    "pydantic>=2.11.9",
    "pynput>=1.8.1",
    "pyperclip>=1.10.0",
    "pystray>=0.19.5",
    "requests>=2.32.5",
    "toml>=0.10.2",
    "win11toast>=0.35",
]

[dependency-groups]
dev = [
    "ipython>=9.5.0",
    "pytest>=8.4.2",
]

[project.gui-scripts]
translate = "translate.__main__:main"

[[tool.uv.index]]
name = "huawei"
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"

[tool.uv.build-backend]
source-include = [
    "translate/fonts/**"
]

