[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "translate"
#version = {attr = "translate.VERSION"}
description = "翻译工具包"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0", # 处理图片的库
    "pydantic>=2.11.9", # 模型校验
    "pynput>=1.8.1", # 快捷键监听
    "pyperclip>=1.10.0", # 剪切板读写
    "pystray>=0.19.5", # 系统托盘创建和管理
    "requests>=2.32.5", # HTTP请求
    "sqlalchemy>=2.0.43", # 数据库读写
    "toml>=0.10.2", # toml读写
    "win11toast>=0.36", # 系统通知
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "translate.VERSION" }

[dependency-groups]
dev = [
    "ipython>=9.5.0",
    "pytest>=8.4.2",
]

[tool.setuptools.package-data]
"translate.zhconv" = ["zhcdict.json"]
"translate" = [
    "resources/LXGWWenKaiMono-Medium.ttf.lzma",
    "resources/app-icon.png"
]


[project.gui-scripts]
translate = "translate.__main__:main"

[project.scripts]
translate-cli = "translate.__main__:main"

[[tool.uv.index]]
name = "huawei"
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"

[tool.uv.build-backend]
source-include = [
    "translate/resources/*"
]
