name: Sync from Remote

on:
  schedule:
    # 每天 UTC 0:00 执行（北京时间 8:00）
    - cron: "2 */6 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Add remote repository
        run: |
          git remote add upstream https://cnb.cool/leecq/ops-toolkit.git || true
          git fetch upstream main
          git merge upstream/main --allow-unrelated-histories || true
          git push origin main

